#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

PYTHON_VERSION="3.5.0"
VIRTUALENV_VERSION="1.11.6"
PCRE_VERSION="8.36"
NGINX_VERSION="1.4.0"
MEMCACHED_VERSION="1.4.15"


# Check for Python and install if absent
if [ ! -f $OPENSHIFT_DATA_DIR'bin/python3' ]; then
    cd $OPENSHIFT_TMP_DIR
    wget http://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz
    tar Jxf Python-${PYTHON_VERSION}.tar.xz
    cd Python-${PYTHON_VERSION}
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install
fi

# Check for virtualenv and install if absent
if [ ! -f $OPENSHIFT_DATA_DIR'bin/virtualenv' ]; then
    $OPENSHIFT_DATA_DIR/bin/pip3 install virtualenv
fi

# Check for existing virtual environment and install if there isn't one
if [ ! -d $OPENSHIFT_HOMEDIR'python/virtenv/venv' ]; then
    $OPENSHIFT_DATA_DIR'bin/virtualenv' -p $OPENSHIFT_DATA_DIR'bin/python3' $OPENSHIFT_DATA_DIR'virtualenv'
fi

if [ ! -d $OPENSHIFT_DATA_DIR'nginx/sbin' ]; then
    cd $OPENSHIFT_TMP_DIR
    wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz
    wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
    tar -xvf pcre-${PCRE_VERSION}.tar.gz
    tar -xvf nginx-${NGINX_VERSION}.tar.gz
    cd nginx-${NGINX_VERSION}
    mkdir $OPENSHIFT_DATA_DIR'nginx'
    ./configure --prefix=$OPENSHIFT_DATA_DIR'nginx' --with-pcre=$OPENSHIFT_TMP_DIR/pcre-${PCRE_VERSION} --with-http_realip_module
    make && make install && make clean
fi

if [ ! -f $OPENSHIFT_DATA_DIR/bin/memcached ]; then
    cd $OPENSHIFT_TMP_DIR
    wget http://memcached.googlecode.com/files/memcached-${MEMCACHED_VERSION}.tar.gz
    tar zxf memcached-${MEMCACHED_VERSION}.tar.gz
    cd memcached-${MEMCACHED_VERSION}
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make && make install
fi

# cleanup
rm -rf $OPENSHIFT_TMP_DIR/*
